# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Verify PR

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '.*'
      - '.github/**'
      - 'install/**'
      - 'README.adoc'
      - '**/README.adoc'
      - '*.ps1'
      - 'public/**'
      - 'static/**'
      - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show event payload
      run: cat ${{ github.event_path }}
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11
    - name: Cache repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Prepare Maven settings.xml
      uses: s4u/maven-settings-action@v2.3.0
      with:
        servers: |
          [{
            "id": "payara-enterprise",
            "username": "${{ secrets.ENTERPRISE_REPO_USER }}",
            "password": "${{ secrets.ENTERPRISE_REPO_PASSWORD }}"
          }]

    - name: Clean snapshot dependencies
      run: "test -d ~/.m2/repository && find ~/.m2/repository/ -name '*-SNAPSHOT' -type d -print0 | xargs -0 rm -r"
      continue-on-error: true

    - name: Build with Maven
      env:
        MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.rto=30000 -Djava.net.preferIPv4Stack=true
      run: mvn -B install --file pom.xml --global-toolchains .github/toolchains.xml

    - name: Archive logs on failure
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: "**/target/*.log*"
